WITH cte([Manual Class], 
         [Pred], 
         [Quality], 
         [Constant], 
         [Sub Tot % Dev], 
         [Basement Under], 
         [LM Storage], 
         [Paved Floor], 
         [Exs], 
         [Sup], 
         [Base MRC], 
         [% Dev], 
         [Sub], 
         [% Complete], 
         [MRC], 
         [Ovrd MRC], 
         [MACM], 
         [# ID Units], 
         [Market RCN], 
         [Eff Yr], 
         [Depr Table], 
         [Dep As], 
         [Phy Depr], 
         [Ext Obs], 
         [Spec Dep], 
         [Tot Dep], 
         [Mkt RCNLD], 
         [Components], 
         [Group Name], 
         [Ext Adj], 
         [Sub Total Mkt], 
         [Model Name], 
         [Tot Lump Sum], 
         [Tot %], 
         [Mkt Adj RCNLD])
     AS (SELECT '0921', 
                'x', 
                '2', 
                5864, 
                9867, 
                NULL, 
                NULL, 
                '203     2.10     $426', 
                'x', 
                'x', 
                10293, 
                NULL, 
                10293, 
                NULL, 
                10293, 
                NULL, 
                1.100, 
                NULL, 
                11323, 
                NULL, 
                NULL, 
                '101100', 
                '35.00%', 
                NULL, 
                NULL, 
                '35.00%     -3,963', 
                7360, 
                'Low Pitch   203       19.72     $4,003', 
                NULL, 
                NULL, 
                7360, 
                NULL, 
                NULL, 
                NULL, 
                7360)
     SELECT *
     FROM cte;