WITH cte([KEY], 
         [Comp], 
         [Rate Type], 
         [Rate Table], 
         [Rate Code], 
         [Rate Amount], 
         [Excess Land], 
         [Zoning], 
         [Acres Curve], 
         [Square Feet], 
         [Sq. Ft. Curve], 
         [Width], 
         [Width Curve], 
         [Depth], 
         [Depth Curve], 
         [# Units], 
         [Unit Curve], 
         [Dimensioned Value], 
         [Total Adjust], 
         [Comp Value], 
         [Total Comp Val], 
         [Acres], 
         [Acres Curve Factor], 
         [Sq. Ft. Curve Factor], 
         [Width Curve Factor], 
         [Depth Curve Factor], 
         [# Unit Hectares], 
         [Unit Curve Factor], 
         [Suppress], 
         [Comp Apprt], 
         [Ovrd Comp Val])
     AS (SELECT 1, 
                '107100', 
                '2', 
                'N', 
                '1011', 
                373700, 
                'x', 
                '', 
                '21362', 
                9266, 
                '', 
                81.0, 
                '', 
                117.0, 
                '', 
                '', 
                '', 
                379094, 
                -37909, 
                341185, 
                341185, 
                0.213, 
                1.0144, 
                '', 
                '', 
                '', 
                '', 
                '', 
                'x', 
                '1000.00%', 
                '')
     SELECT *
     FROM [cte]
     ORDER BY [KEY];