WITH cte([Manual Class], 
         [Default Quality], 
         [Roof Cover], 
         [Roof Cover 2], 
         [Year Built], 
         [Year Remodelled], 
         [Stage Recreational], 
         [Quality %], 
         [Design %], 
         [Iregg %], 
         [Int Feat %], 
         [Cath Entry %], 
         [Split Level %], 
         [Attic %], 
         [Other %], 
         [Pred], 
         [Excess], 
         [Suppress])
     AS (SELECT '0142  10.00%  2 Sty Sfd - After 1960 - Modern Std', 
                '3', 
                'Asphalt Shingles', 
                '', 
                '1920', 
                '2003', 
                '', 
                '10.00%', 
                '', 
                '', 
                '', 
                '', 
                '', 
                '', 
                '', 
                'x', 
                'x', 
                'x')
     SELECT *
     FROM cte;