/* Formatted on 23-May-19 2:10:06 PM (QP5 v5.326) */
SELECT "Alternate Id",
       "Area Code",
       "Batch Computation/Change",
       "Current Record Indicator",
       "Date Of Last Batch Change",
       "Deactivation Date",
       "Description",
       "Expropriation Flag",
       "Farm Adjusted Income",
       "Farm Adjusted Income Code",
       "Farm Calculated Total Value",
       "Farm Dominant Use",
       "Farm Income Ratio",
       "Farm Next Income Review Date",
       "Farm Next Lease Review Date",
       "Farm Reported Income",
       "Farm Status",
       "Farm Threshold Income Year",
       "Farm Threshold Value",
       "Farm Total Hectares",
       "Farm Total Hectares Override",
       FARMTOTVALOVR,
       "Iasworld Transaction Number",
       "Iasworld Unique Row Identifier",
       "Jur_Ias",
       "Jurisdiction",
       "Last Maintenance Date",
       "Linear Calculated Total Length",
       "Linear Calculated Total Value",
       "Linear Construction Year",
       "Linear Crs",
       "Linear Project Number",
       "Managed Forest Cut Timber",
       "Managed Forest Harvest Flag",
       "Managed Forest Region",
       "Managed Forest Total Area",
       MFORHRVRECDT,
       MFORHRVREQDT,
       MFORTOTBLVAL,
       MFORTOTCTVAL,
       "Plant Calculated Total Value",
       "Plant Category",
       "Plant Closure Year",
       "Plant Department Count",
       "Plant Improvement Count",
       "Plant Primary Division",
       "Plant Type",
       PLTOTBASECOST,
       "Processing Status",
       REGID,
       "Regulated Type",
       "Remarks",
       "Roll Year",
       UPD_STATUS,
       "User Date 1",
       "User Date 10",
       "User Date 2",
       "User Date 3",
       "User Date 4",
       "User Date 5",
       "User Date 6",
       "User Date 7",
       "User Date 8",
       "User Date 9",
       "User Defined Field 1",
       "User Defined Field 10",
       "User Defined Field 11",
       "User Defined Field 12",
       "User Defined Field 13",
       "User Defined Field 14",
       "User Defined Field 15",
       "User Defined Field 16",
       "User Defined Field 17",
       "User Defined Field 18",
       "User Defined Field 19",
       "User Defined Field 2",
       "User Defined Field 20",
       "User Defined Field 3",
       "User Defined Field 4",
       "User Defined Field 5",
       "User Defined Field 6",
       "User Defined Field 7",
       "User Defined Field 8",
       "User Defined Field 9",
       "User Id Of Last Maintenance",
       "Userval 1",
       "Userval 10",
       "Userval 2",
       "Userval 3",
       "Userval 4",
       "Userval 5",
       "Userval 6",
       "Userval 7",
       "Userval 8",
       "Userval 9",
       "Version Number Of This Record"
  FROM BCA_COMMON.REGMAST_VW;