/* Formatted on 23-May-19 1:41:48 PM (QP5 v5.326) */
SELECT "Abandoned Flag",
       "Base Cost For Plant",
       "Batch Computation/Change",
       "Bundle Size For Cable",
       "Closure Year",
       "Cost Source",
       "Cost Update Code",
       COSTADJ,
       "Current",
       "Dark Fibre Flag",
       "Date Of Last Batch Change",
       "Deactivation Date",
       "Department Id",
       "Depreciation",
       "Depreciation Table",
       "Economic Depreciation",
       "Economic Reason",
       "Effective Year",
       "Exclude Idc Factor",
       "Functional Depreciation",
       "Functional Reason",
       "Iasworld Transaction Number",
       "Iasworld Unique Row Identifier",
       "Idcfact",
       "Improvement Code",
       "Improvement Number",
       "Improvement Remarks",
       "Install Code For Fibre",
       "Jur_Ias",
       "Kilometers",
       "Last Maintenance Date",
       "Line Number",
       "Miles",
       "Number Of Fibres",
       "Observed Depreciation",
       "Observed Reason",
       "Override Rcn",
       "Override Rcn Reason",
       "Plant Improvement Cost Year",
       "Plupdfact",
       "Processing Status",
       "Property Id",
       "Rate",
       "Rcn Value",
       "Rcnld Adjusted Value",
       "Rcnld Override Value",
       "Rcnld Value",
       "Regulated Entity Id",
       "Regulated Type",
       "Roll Year",
       "Sequence",
       SOURCE_DIV,
       "Suppress Flag",
       "Suspended Flag",
       "Units",
       UPD_STATUS,
       "User Date 1",
       "User Date 10",
       "User Date 2",
       "User Date 3",
       "User Date 4",
       "User Date 5",
       "User Date 6",
       "User Date 7",
       "User Date 8",
       "User Date 9",
       "User Field 1",
       "User Field 10",
       "User Field 2",
       "User Field 3",
       "User Field 4",
       "User Field 5",
       "User Field 6",
       "User Field 7",
       "User Field 8",
       "User Field 9",
       "User Id Of Last Maintenance",
       "Userval Field 1",
       "Userval Field 10",
       "Userval Field 2",
       "Userval Field 3",
       "Userval Field 4",
       "Userval Field 5",
       "Userval Field 6",
       "Userval Field 7",
       "Userval Field 8",
       "Userval Field 9",
       "Year Built"
  FROM BCA_COMMON.REGIMP_VW;